### ISSUE TITLE
Ambiguous Requirements with regards to double digit output

### ISSUE THREAD

**Issue by turboMaCk** [otobrglez/compression-puzzle#29]
Related to my comment https://github.com/otobrglez/compression-puzzle/pull/28#discussion_r800222450

there is slight ambiguity in output produce by the program. consider this input:

`AAAAAAAAAAA` could produce `11A`

now imagine digit in the input: `1` will produce `11`

This means that output for the input 111x A sequence would be the same as for `1A` (`111A`).

This is not a problem given there is only one simple example but it sort of makes it hard to say how would truly correct implementation look like.

**Comment by otobrglez** [comment]
That is a very good point. I've added the "4th" rule/instruction that now states:

> 4. [Assume that](https://github.com/otobrglez/compression-puzzle/issues/29)[](https://github.com/otobrglez/compression-puzzle#additional-qa) the input is always a sequence of ASCII upper-case characters (no numbers or symbols).

Tnx!
