### ISSUE TITLE
Python scripts don't seem to get invoked

### ISSUE THREAD

**Issue by refaktor** [otobrglez/compression-puzzle#33]
It seems python3 doesn't run scripts with

    python3 src/python/*.py 

like it's written in the make file. Maybe there is a more elegant solution but this works

    find src/python/ -name "*.py" -print0 | xargs -0 -n 2 python3

**Comment by otobrglez** [comment]
@refaktor Good idea. The only thing missing in your solution is that I want to exclude the benchmark.py from the scripts that should run. Find a way to exclude that and open with modified `Makefile` PR to win this one. :)

**Comment by otobrglez** [comment]
Tnx for reporting this.  I've fixed it.
